apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  labels:
    app: web-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      serviceAccountName: web-client-sa
      imagePullSecrets:
        - name: ghcr-creds
      containers:
      - name: web-client
        image: ghcr.io/sglee487/loopin-client:d93ccfb48d0c3228944680f327085631c006757d
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_BASE_URL
          value: "https://api.loopin.bid"

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: web-client-config-volume
        configMap:
          name: web-client-config
